name: hydroponic_monitor
description: A cross-platform Flutter application to monitor and control hydroponic systems
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter
  
  # State Management & DI
  hooks_riverpod: ^2.5.2
  flutter_hooks: ^0.20.5
  
  # Navigation
  go_router: ^14.2.7
  
  # Network & Data
  dio: ^5.7.0
  mqtt_client: ^10.2.0
  influxdb_client: ^3.0.0
  
  # Serialization
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  
  # Charts & UI
  fl_chart: ^0.69.0
  
  # Storage & Security
  flutter_secure_storage: ^9.2.2
  
  # Environment & Configuration
  flutter_dotenv: ^5.1.0
  
  # Icons & Material Design
  material_color_utilities: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting
  flutter_lints: ^4.0.0
  
  # Code Generation
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  
  # Testing
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  
  # Uncomment when adding assets
  # assets:
  #   - images/
  #   - .env