# --- MQTT -> Sensors (per-sensor JSON) ---
[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  username = "telegraf"
  password = "$MQTT_PASS"
  topics  = ["grow/tent/+/sensor/+/+/state"]
  qos = 0
  persistent_session = true
  client_id = "telegraf-grow-sensors"
  connection_timeout = "30s"
  data_format = "json_v2"

  [[inputs.mqtt_consumer.json_v2]]
    measurement_name = "env"
    [[inputs.mqtt_consumer.json_v2.object]]
      path = ""
      timestamp_path   = "ts"
      timestamp_format = "2006-01-02T15:04:05Z07:00"
      tags   = ["unit"]
      fields = [
        { path = "value",    type = "float" },
        { path = "accuracy", type = "float", optional = true }
      ]

  [[inputs.mqtt_consumer.topic_parsing]]
    topic = "grow/!scope/!node/sensor/!type/!id/state"
    tags  = ["scope","node","type","id"]