# --- MQTT -> Actuator State (numeric 1/0) ---
[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  # Support both authenticated and anonymous access for test environments
  username = "${MQTT_PASS:+telegraf}"  # Only set username if MQTT_PASS is not empty
  password = "$MQTT_PASS"
  topics  = ["grow/tent/+/actuator/+/+/state"]
  qos = 1
  persistent_session = true
  client_id = "telegraf-grow-actuators"
  data_format = "json_v2"

  [[inputs.mqtt_consumer.json_v2]]
    measurement_name = "actuator_state"
    [[inputs.mqtt_consumer.json_v2.object]]
      path = ""
      timestamp_path   = "ts"
      timestamp_format = "2006-01-02T15:04:05Z07:00"
      fields = [
        { path = "state",       type = "int"    },  # 1/0 numeric
        { path = "level",       type = "string", optional = true },
        { path = "power_W",     type = "float",  optional = true },
        { path = "request_id",  type = "string", optional = true }
      ]

  [[inputs.mqtt_consumer.topic_parsing]]
    topic = "grow/!scope/!node/actuator/!type/!id/state"
    tags  = ["scope","node","type","id"]