name: Copilot setup (install Flutter)

on:
  # Copilot coding agent looks for this file by name and reuses its steps
  workflow_call:
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.35.2'
  
jobs:
  copilot-setup-steps:   # 👈 MUST be named exactly this
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # OPTIONAL — install Flutter if your agent needs `flutter` commands
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:"
      
      - name: Get dependencies
        run: flutter pub get

      # Sanity checks so you can see versions in logs
      - name: Show tool versions
        run: |
          which dart && dart --version
          which flutter && flutter --version || true

