name: Auto Format Code on PR

on:
  pull_request:
    types: [opened, synchronize]
    branches: [ main, develop ]

jobs:
  format:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository  # Only run on same repo PRs
    
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: "3.9"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Get dependencies
        run: flutter pub get

      - name: Check if formatting is needed
        id: check-format
        run: |
          # Check if any files need formatting
          if ! dart format --output none --set-exit-if-changed .; then
            echo "needs_format=true" >> $GITHUB_OUTPUT
          else
            echo "needs_format=false" >> $GITHUB_OUTPUT
          fi

      - name: Format code
        if: steps.check-format.outputs.needs_format == 'true'
        run: dart format .

      - name: Commit formatted code
        if: steps.check-format.outputs.needs_format == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "🔧 Auto-format code with dart format"
            git remote set-url origin https://x-access-token:${{ secrets.WRITE_ACTION_SECRET }}@github.com/${{ github.repository }}
            git push
          fi

      - name: Comment on PR
        if: steps.check-format.outputs.needs_format == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🔧 Code has been automatically formatted with `dart format .`'
            })
